services:
  backend:
    build: ./back
    container_name: game-backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./front
    container_name: game-frontend
    ports:
      - "80:8501"
    depends_on:
      - backend
    restart: always
